# GitHub Actions Workflow: Build .csproj and Create Release
#
# WHAT THIS DOES:
# 1. Triggers automatically when you push a new tag (e.g., "v1.0.0").
# 2. Can also be triggered manually from the "Actions" tab.
# 3. If triggered by a tag, it creates a full release with that version number.
# 4. If triggered manually, it creates/updates a "Pre-release" for testing.
# 5. Publishes the entire application as a single, self-contained .exe file.
# 6. Uploads the single .exe file as a permanent asset to the release.
#
# HOW TO USE:
# 1. To create a final release, push a new tag:
#    git tag v1.0.3
#    git push origin v1.0.3
# 2. To create a test build, run the workflow manually.
# 3. On the Releases page, you can now download the single .exe file directly.

name: Build and Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tags like v1.0.0, v1.2.3, etc.
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write # This permission is required to create a release

    steps:
    # Step 1: Check out your repository code so the workflow can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up MSBuild.
    - name: Add msbuild to path
      uses: microsoft/setup-msbuild@v2

    # Step 3: Restore NuGet packages for the project
    - name: Restore NuGet packages
      run: nuget restore OracleOptimizer/OracleOptimizer.csproj

    # Step 4: Publish the application as a single, self-contained file
    - name: Publish as single file
      # This command uses the 'publish' target with specific properties:
      # /p:PublishSingleFile=true - Bundles the app into one .exe
      # /p:SelfContained=true - Includes the .NET runtime in the .exe
      # /p:RuntimeIdentifier=win-x64 - Specifies the target OS and architecture
      run: >
        msbuild.exe OracleOptimizer/OracleOptimizer.csproj /t:publish
        /p:Configuration=Release
        /p:PublishSingleFile=true
        /p:SelfContained=true
        /p:RuntimeIdentifier=win-x64

    # Step 5: Create a GitHub Release and upload the single .exe file
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        # The 'files' option now points to the single .exe in the publish directory.
        files: 'OracleOptimizer/bin/Release/net8.0-windows/win-x64/publish/OracleOptimizer.exe'
        # If run manually, name the release "Nightly Build". Otherwise, use the tag name.
        name: ${{ github.event_name == 'workflow_dispatch' && 'Nightly Build' || github.ref_name }}
        # If run manually, mark it as a pre-release.
        prerelease: ${{ github.event_name == 'workflow_dispatch' }}
        # If run manually, create/update a tag called "nightly". Otherwise, use the pushed tag.
        tag_name: ${{ github.event_name == 'workflow_dispatch' && 'nightly' || github.ref_name }}
