# GitHub Actions Workflow: Build .csproj and Create Release
#
# WHAT THIS DOES:
# 1. Triggers automatically when you push a new tag (e.g., "v1.0.0").
# 2. Can also be triggered manually from the "Actions" tab.
# 3. If triggered by a tag, it creates a full release with that version number.
# 4. If triggered manually, it creates/updates a "Pre-release" for testing.
# 5. Uploads your compiled .exe file as a permanent asset to the release.
#
# HOW TO USE:
# 1. To create a final release, push a new tag:
#    git tag v1.0.1
#    git push origin v1.0.1
# 2. To create a test build, go to the Actions tab and click "Run workflow".
#    Look for the "nightly" pre-release on your repository's Releases page.

name: Build and Create Release

on:
  push:
    tags:
      - 'v*.*.*' # Triggers the workflow on version tags like v1.0.0, v1.2.3, etc.
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  build-and-release:
    runs-on: windows-latest
    permissions:
      contents: write # This permission is required to create a release

    steps:
    # Step 1: Check out your repository code so the workflow can access it
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up MSBuild.
    - name: Add msbuild to path
      uses: microsoft/setup-msbuild@v2

    # Step 3: Restore NuGet packages for the project
    - name: Restore NuGet packages
      run: nuget restore OracleOptimizer/OracleOptimizer.csproj

    # Step 4: Build the project.
    - name: Build project
      run: msbuild.exe OracleOptimizer/OracleOptimizer.csproj /p:Configuration=Release

    # Step 5: Create a GitHub Release and upload the .exe as an asset
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        # The 'files' option points to your compiled executable.
        files: '**/bin/Release/**/*.exe'
        # If run manually, name the release "Nightly Build". Otherwise, use the tag name.
        name: ${{ github.event_name == 'workflow_dispatch' && 'Nightly Build' || github.ref_name }}
        # If run manually, mark it as a pre-release.
        prerelease: ${{ github.event_name == 'workflow_dispatch' }}
        # If run manually, create/update a tag called "nightly". Otherwise, use the pushed tag.
        tag_name: ${{ github.event_name == 'workflow_dispatch' && 'nightly' || github.ref_name }}
